### ISSUE TITLE
Glitches and turns off, Video stops after a while and then restart

### ISSUE THREAD

**Issue by nasimsamin86** [Taiizor/Sucrose#100]
**Bug Description**
1. Glitches and turns off, 
2. Video stops after a while and then restart

**Comment by Taiizor** [comment]
Please share your log files with me by following the instructions below:

Right click on the system tray icon -> Report Issue -> Create Log File
or
Open Sucrose settings (Gear icon) top-right -> System -> Log Files -> Create
or 
Navigate to the Appdata folder `C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`
