### ISSUE TITLE
error then installing. windows 11

### ISSUE THREAD

**Issue by spetauskas** [Taiizor/Sucrose#102]
![image](https://github.com/user-attachments/assets/979b0b5b-ed62-4527-9a47-bad6658bd43d)

**Comment by Taiizor** [comment]
You're encountering an error while creating the application shortcut. Based on the error, it seems the directory where these shortcuts are supposed to be created either doesn't exist or there's an access issue. Could you try running the application with administrator privileges during installation?

**Comment by Taiizor** [comment]
@spetauskas Could you let me know which version of Sucrose you are trying to install?

**Comment by spetauskas** [comment]
today downloaded this file:
windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-x64

**Comment by Taiizor** [comment]
> today downloaded this file: windowsdesktop-runtime-9.0.0-rc.2.24474.4-win-x64

@spetauskas If you are trying to install the file [Sucrose_Bundle_.NET_9.0_x64_24.10.21.0.exe](https://github.com/Taiizor/Sucrose/releases/download/v24.10.21.0/Sucrose_Bundle_.NET_9.0_x64_24.10.21.0.exe), please try running it with administrator privileges.

**Comment by Taiizor** [comment]
@spetauskas If you still encounter the same error after running with administrator privileges, please run the application in the archive below and send me a screenshot of it.

[Sucrose.Debug.zip](https://github.com/user-attachments/files/17491485/Sucrose.Debug.zip)

**Comment by Taiizor** [comment]
@spetauskas If you still encounter the same error after running with administrator privileges, please run the application in the archive below and send me a screenshot of it.

[Sucrose.Debug.zip](https://github.com/user-attachments/files/17491654/Sucrose.Debug.zip)

**Comment by Taiizor** [comment]
@spetauskas You didn't respond, but in the next version, shortcut errors are set to be ignored if they occur.
