### ISSUE TITLE
Not working after wake from sleep

### ISSUE THREAD

**Issue by cosmyn31** [Taiizor/Sucrose#103]
**Bug Description**
After PC wake from sleep mode wallpaper is not responding. I have to doubleclick to open app from tray and re-apply it in order to have it move again.

**To Reproduce**
1. put moving wallpaper
2. put computer to sleep mode
3. wake computer from sleep mode
4. wallpaper is not moving anymore

**Expected Behavior**
Wallpaper Engine should reload and restart wallpaper automatically.

**Desktop (please complete the following information):**
- OS: Windows 11 build 22621.4317
- Which wallpaper was running at the time: i try serveral of them: Neo Matrix, DNA Medical, Forrest Black BMW M8, Windows 11, Fluid simulation, etc.

**Additional Context**

**Log File (Important)**
[sucrose_log_20241028_233337.zip](https://github.com/user-attachments/files/17549133/sucrose_log_20241028_233337.zip)

**Comment by Taiizor** [comment]
I'm aware of the issue related to sleep mode. I'll be releasing an update about it as soon as possible. You can follow the progress in the issue you've opened.

**Comment by Taiizor** [comment]
@cosmyn31 In the next update, performance settings related to the operating system, as shown in the image below, will be added. With these settings, your issue should be resolved.

![Sucrose-Performance-Settings](https://github.com/user-attachments/assets/1998cf4a-b283-4c8f-8e8a-6e6a517917c7)
