### ISSUE TITLE
Walpaper dosent work

### ISSUE THREAD

**Issue by Alexgame642** [Taiizor/Sucrose#105]
**Bug Description**

**To Reproduce**

**Expected Behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
- OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional Context**

**Log File (Important)**
Share the diagnostic files by:
Right click on the system tray icon -> Report Issue -> Create Log File
or
Open Sucrose settings (Gear icon) top-right -> System -> Log Files -> Create
or 
Navigate to the Appdata folder `C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`

**Comment by Taiizor** [comment]
@Alexgame642 You haven't provided any details about the wallpaper not working. Please give more detailed information so I can assist you better.
