### ISSUE TITLE
When using live wallpapers, computer doesn't sleep properly

### ISSUE THREAD

**Issue by Little-Data** [Taiizor/Sucrose#106]
**Bug Description**
When using live wallpapers, computer doesn't sleep properly.
I've made sure that the sleep-related settings in the system settings are turned on.

**To Reproduce**

Using live wallpapers

**Expected Behavior**
When using live wallpapers, the system should sleep normally.

**Desktop (please complete the following information):**
- OS: Windows 11 24H2

**Log File (Important)**
Share the diagnostic files by:

[sucrose_log_20241127_224045.zip](https://github.com/user-attachments/files/17935943/sucrose_log_20241127_224045.zip)

**Comment by Taiizor** [comment]
Yes, you're right. It prevents entering sleep mode. I will test solutions regarding this issue in the coming days and share the results here.

**Comment by Taiizor** [comment]
Now, when playing gif or video with MpvPlayer, issues such as the screensaver not starting or the system not entering sleep mode no longer occur.

**Comment by Taiizor** [comment]
By default, "Stay Awake" is disabled and supported engines and extensions (currently only MpvPlayer) will operate without preventing sleep mode or the screensaver. If enabled, it will block sleep mode and screensaver for all engines and extensions as well.

![Sucrose-Stay-Awake](https://github.com/user-attachments/assets/4f9a927b-1797-46f5-a937-1a4890caa525)
