### ISSUE TITLE
The app bugs out and hangs

### ISSUE THREAD

**Issue by KKian004** [Taiizor/Sucrose#76]
**Bug Description**

**To Reproduce**

**Expected Behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional Context**

**Log File (Important)**
Share the diagnostic files by:
Open Sucrose settings (Gear icon) top-right -> System -> Log Files -> Create
or 
Navigate to the Appdata folder `C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`

**Comment by KKian004** [comment]
Whenever the app runs it plays for a few seconds then crashes.

**Comment by Taiizor** [comment]
You haven't filled in the necessary fields above related to your issue. Therefore, I can't solve your problem.
