### ISSUE TITLE
The app bugs out and crashes

### ISSUE THREAD

**Issue by KKian004** [Taiizor/Sucrose#77]
**Bug Description**

**To Reproduce**

**Expected Behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional Context**

**Log File (Important)**
Share the diagnostic files by:
Open Sucrose settings (Gear icon) top-right -> System -> Log Files -> Create
or 
Navigate to the Appdata folder `C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`

**Comment by KKian004** [comment]
Am on windows 11. The issue that pops up is when i run the app it crashes for a few seconds then closes itself. I tried adjusting all the settings but it's not working out. I can't provide the log because the app isn't opening .

**Comment by Taiizor** [comment]
Here is a directory on how to access the error logs of the application:

`C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`

You can archive and send the error logs from this location.
