### ISSUE TITLE
crashing again and again when i am opening it 

### ISSUE THREAD

**Issue by Peterparker786** [Taiizor/Sucrose#83]
**Bug Description**

**To Reproduce**

**Expected Behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional Context**

**Log File (Important)**
Share the diagnostic files by:
Open Sucrose settings (Gear icon) top-right -> System -> Log Files -> Create
or 
Navigate to the Appdata folder `C:\Users\<UserName>\AppData\Roaming\Sucrose\Log`

**Comment by Taiizor** [comment]
Please fill in the above issue template according to the error you received and provide me with detailed information. Otherwise, I cannot helping you.

**Comment by Taiizor** [comment]
@Peterparker786 Would you provide the necessary information? Otherwise, I'll close the issue.
