### ISSUE TITLE
Url & Web Type Theme is not Interactive

### ISSUE THREAD

**Issue by yepplus** [Taiizor/Sucrose#86]
**Bug Description**
Web Type Theme is not Interactive

**To Reproduce**
1. Select a web type theme and activate it

**Screenshots/Video**
https://github.com/Taiizor/Sucrose/assets/71744069/2be58c9d-5b25-421e-aa22-0c02e5d76df7

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 (OS Insider Version 22621.2281)

**Log File (Important)**
[sucrose_log_20240513_120238.zip](https://github.com/Taiizor/Sucrose/files/15289970/sucrose_log_20240513_120238.zip)

**Comment by Taiizor** [comment]
Thank you for taking the time to report this.
This feature is currently in preparation and will be active in the next Developer Release.

![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/cf4f3f1d-8764-4ebe-91da-12a986d852df)

**Comment by yepplus** [comment]
Thanks a lot. Can't wait for the next Developer Release😄

**Comment by Taiizor** [comment]
The following video demonstrates mouse and keyboard interactions for WebView engine. The only known issue is that the mouse wheel scrolling event does not work.

https://github.com/Taiizor/Sucrose/assets/41683699/9dc06921-c857-4b53-b50d-88ce67fe5cf1

**Comment by yepplus** [comment]
Wow, cool! Incredible work🤩

**Comment by Taiizor** [comment]
> The following video demonstrates mouse and keyboard interactions for WebView engine. The only known issue is that the mouse wheel scrolling event does not work.
> 
>  2024-05-15_16-49-00.mp4


Mouse wheel scrolling for WebView is now functional.

https://github.com/Taiizor/Sucrose/assets/41683699/ad364922-b04a-4bfd-b459-a4f8af22ab7c

**Comment by Taiizor** [comment]
The following video demonstrates mouse and keyboard interactions for CefSharp. There are currently no known issues.

https://github.com/Taiizor/Sucrose/assets/41683699/719d105a-55cf-41d9-8452-db2700681982

**Comment by Taiizor** [comment]
The wallpaper interaction feature will be available in the next release.
