### ISSUE TITLE
problem with the information need to be filled to use custom live wallpaper

### ISSUE THREAD

**Issue by Anuresh-greylike** [Taiizor/Sucrose#87]
Will you guys be able to put the example on how to fill the information or make it optional when using custom wallpaper, just download a video and wanted to use in as soon as possible but no i gotta fill information first.

**Comment by Taiizor** [comment]
The mandatory information to enter when creating a theme:

Title, Description, Author and Contact (Email or Url)

Optional information:

Thumbnail, Preview and Tags

I might provide a more convenient usage for this topic in the future, but for now, filling out the mandatory information I provided above is necessary.

**Comment by Taiizor** [comment]
For Gif, Web, Video and Application, now themes can be quickly created via drag and drop without filling out fields. However, users can edit these fields if desired.

The Title field is taken from the selected file name.
The Description field is created by combining the selected file name with the theme type.

https://github.com/Taiizor/Sucrose/assets/41683699/ea42249b-f94f-42cc-b2f3-ce1d54b17200

For Url and YouTube type themes, the Author and Contact fields are automatically populated. Users can still edit these fields if they wish. The remaining fields, Title and Description, need to be filled out by the user.

![Sucrose](https://github.com/Taiizor/Sucrose/assets/41683699/22cc4eec-6f7c-44e3-a744-c6a83cb90330)

The Author field is derived from your Windows username.
The Contact field combines your Windows username with either an email address or a url.

**Comment by Taiizor** [comment]
@Anuresh-greylike If you feel adequately informed about the topic, I'll close this issue.
