### ISSUE TITLE
Want like a loop feature 

### ISSUE THREAD

**Issue by furjac** [Taiizor/Sucrose#89]
Like loop through all wallpaper in the app in given interval of time

**Comment by Taiizor** [comment]
The feature you refer to as `Loop` is called `Wallpaper Cycling` in the application. I've shared a video below related to this feature. If you watch it, you'll understand that this is exactly what you're looking for.

https://www.youtube.com/watch?v=7u8xB31pNXY

**Comment by furjac** [comment]
Thank you so much love the app amazing
