### ISSUE TITLE
cannot Download any wallpaper

### ISSUE THREAD

**Issue by darksubhbkl** [Taiizor/Sucrose#91]
when i try to downaloda any wallpaper it does not let me dowanload

**Comment by Taiizor** [comment]
Every theme in the store is released with a minimum version requirement for Sucrose. To add the theme to your library, you must meet this requirement. You can check for updates by right-clicking the Sucrose system tray icon in the taskbar.

![Sucrose-TrayIcon](https://github.com/Taiizor/Sucrose/assets/41683699/ed144d14-2402-4ffa-8357-d670e475e7db)

**Comment by Taiizor** [comment]
If your issue is not related to this, please provide more information about the problem.
