### ISSUE TITLE
I had issue during the installation

### ISSUE THREAD

**Issue by Abdul35MHz** [Taiizor/Sucrose#92]
Hello there i had issue during the installation if you can see snapshot i took it also to know i installed .net. 

please support. 
![Screenshot 2024-07-31 150611](https://github.com/user-attachments/assets/db0fbfa8-0af6-43d0-a0cf-50f95c7d2af4)
![Screenshot 2024-07-31 150213](https://github.com/user-attachments/assets/3c9056f7-4243-4692-b74c-c7b98ccc4bc3)

**Comment by Taiizor** [comment]
You are encountering an error while creating the application shortcut. Please check the file path `C:\Users\<UserName>\AppData\Local\Sucrose\Sucrose.Launcher`.

**Comment by Taiizor** [comment]
@Abdul35MHz Have you checked it? Is there such a directory?

**Comment by Abdul35MHz** [comment]
yes i found the exe application in the path thanks a lot. you are the best

**Comment by Taiizor** [comment]
> yes i found the exe application in the path thanks a lot. you are the best

Your issue has been partially resolved, but to understand the root cause of the error, could I send you a simple application? Could you run it and send me a screenshot?

**Comment by Taiizor** [comment]
> > yes i found the exe application in the path thanks a lot. you are the best
> 
> Your issue has been partially resolved, but to understand the root cause of the error, could I send you a simple application? Could you run it and send me a screenshot?

You can download the application [here](https://github.com/user-attachments/files/16448033/Debug.zip). These are the [VirusTotal](https://www.virustotal.com/gui/file/ed47390a206de681634130f5f34964fddb07f575d60ab0eed23bb5c6713c3168) results for the application. When you run the application, you should see a window like the one in the image below. Please take a screenshot of the entire window and send it to me.

**Comment by Taiizor** [comment]
> > > yes i found the exe application in the path thanks a lot. you are the best
> > 
> > 
> > Your issue has been partially resolved, but to understand the root cause of the error, could I send you a simple application? Could you run it and send me a screenshot?
> 
> You can download the application [here](https://github.com/user-attachments/files/16448033/Debug.zip). These are the [VirusTotal](https://www.virustotal.com/gui/file/ed47390a206de681634130f5f34964fddb07f575d60ab0eed23bb5c6713c3168) results for the application. When you run the application, you should see a window like the one in the image below. Please take a screenshot of the entire window and send it to me.
> 
> ![Sucrose-Debug](https://private-user-images.githubusercontent.com/41683699/354027576-7417c204-7373-4264-bbd3-deb7647539e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTg3NDQsIm5iZiI6MTcyMjYxODQ0NCwicGF0aCI6Ii80MTY4MzY5OS8zNTQwMjc1NzYtNzQxN2MyMDQtNzM3My00MjY0LWJiZDMtZGViNzY0NzUzOWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE3MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NjUwZDBjZjVlODIwZTZkM2RkMTcyYzczNzk1ZmZjNmQ1ZmRiN2JiZWQ5N2IyM2M5YTg3MWEyNTcyOTU4NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U94jQEweGMMo8lf5DPU4ArdOVUxqsEQyliQlVB7ScSo)

@Abdul35MHz Will you do what I suggested here? Because if you don't, it will be more difficult to solve this problem and keep your application up to date.
