### ISSUE TITLE
cant run restore

### ISSUE THREAD

**Issue by arsaey** [Taiizor/Sucrose#93]
when i run dotnet restore Sucrose.sln

    C:\Sucrose-develop\src\Project\Sucrose.Watchdog\Sucrose.Watchdog.csproj : error NU1102: Unable to find package System.ComponentModel.Annotations with version (>= 6.0.0-preview.5.21227.3) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Watchdog\Sucrose.Watchdog.csproj : error NU1102:   - Found 57 version(s) in nuget.org [ Nearest version: 6.0.0-preview.4.21253.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Watchdog\Sucrose.Watchdog.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Project\Sucrose.Watchdog\Sucrose.Watchdog.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Watchdog\Sucrose.Watchdog.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Watchdog\Sucrose.Watchdog.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Project\Sucrose.Reportdog\Sucrose.Reportdog.csproj : error NU1102: Unable to find package System.ComponentModel.Annotations with version (>= 6.0.0-preview.5.21227.3) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Reportdog\Sucrose.Reportdog.csproj : error NU1102:   - Found 57 version(s) in nuget.org [ Nearest version: 6.0.0-preview.4.21253.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Reportdog\Sucrose.Reportdog.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Project\Sucrose.Reportdog\Sucrose.Reportdog.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Reportdog\Sucrose.Reportdog.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Reportdog\Sucrose.Reportdog.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Project\Sucrose.Property\Sucrose.Property.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Property\Sucrose.Property.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Property\Sucrose.Property.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Project\Sucrose.Commandog\Sucrose.Commandog.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Commandog\Sucrose.Commandog.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Commandog\Sucrose.Commandog.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Project\Sucrose.Backgroundog\Sucrose.Backgroundog.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Backgroundog\Sucrose.Backgroundog.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Project\Sucrose.Backgroundog\Sucrose.Backgroundog.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.Xavier\Sucrose.Live.Xavier.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Xavier\Sucrose.Live.Xavier.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Xavier\Sucrose.Live.Xavier.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Portal\Sucrose.Portal\Sucrose.Portal.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Portal\Sucrose.Portal\Sucrose.Portal.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Portal\Sucrose.Portal\Sucrose.Portal.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.Vexana\Sucrose.Live.Vexana.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Vexana\Sucrose.Live.Vexana.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Vexana\Sucrose.Live.Vexana.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.Nebula\Sucrose.Live.Nebula.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Nebula\Sucrose.Live.Nebula.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Nebula\Sucrose.Live.Nebula.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.WebView\Sucrose.Live.WebView.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.WebView\Sucrose.Live.WebView.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.WebView\Sucrose.Live.WebView.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.MpvPlayer\Sucrose.Live.MpvPlayer.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.MpvPlayer\Sucrose.Live.MpvPlayer.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.MpvPlayer\Sucrose.Live.MpvPlayer.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Update\Sucrose.Update\Sucrose.Update.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Update\Sucrose.Update\Sucrose.Update.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Update\Sucrose.Update\Sucrose.Update.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.Aurora\Sucrose.Live.Aurora.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Aurora\Sucrose.Live.Aurora.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.Aurora\Sucrose.Live.Aurora.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Launcher\Sucrose.Launcher\Sucrose.Launcher.csproj : error NU1102: Unable to find package System.ComponentModel.Annotations with version (>= 6.0.0-preview.5.21227.3) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Launcher\Sucrose.Launcher\Sucrose.Launcher.csproj : error NU1102:   - Found 57 version(s) in nuget.org [ Nearest version: 6.0.0-preview.4.21253.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Launcher\Sucrose.Launcher\Sucrose.Launcher.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Launcher\Sucrose.Launcher\Sucrose.Launcher.csproj : error NU1605: Warning As Error: Detected package downgrade: System.Management from 9.0.0-preview.7.24363.5 to 9.0.0-preview.6.24327.7. Reference the package directly from the project to select a different version.  [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Launcher\Sucrose.Launcher\Sucrose.Launcher.csproj : error NU1605:  Sucrose.Launcher -> Skylark.Wing 3.1.5.9 -> System.Management (>= 9.0.0-preview.7.24363.5)  [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Launcher\Sucrose.Launcher\Sucrose.Launcher.csproj : error NU1605:  Sucrose.Launcher -> System.Management (>= 9.0.0-preview.6.24327.7) [C:\Sucrose-develop\src\Sucrose.sln]
    C:\Sucrose-develop\src\Live\Sucrose.Live.CefSharp\Sucrose.Live.CefSharp.csproj : error NU1102: Unable to find package System.Management with version (>= 9.0.0-preview.7.24363.5) [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.CefSharp\Sucrose.Live.CefSharp.csproj : error NU1102:   - Found 76 version(s) in nuget.org [ Nearest version: 9.0.0-preview.6.24327.7 ] [C:\Sucrose-develop\src\Sucrose.sln]
C:\Sucrose-develop\src\Live\Sucrose.Live.CefSharp\Sucrose.Live.CefSharp.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\Sucrose-develop\src\Sucrose.sln]

Restore failed with errors in 646.2s

**Comment by Taiizor** [comment]
You’re encountering this error because some necessary packages are being loaded from different sources. You need to add the source `dotnet9` with the URL `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json` to your NuGet sources.

![NuGet](https://github.com/user-attachments/assets/8f1c2513-d822-464c-94c8-d3a7a51eaebe)

If you wait a bit, I can include this change in the project for you.

**Comment by arsaey** [comment]
Thanks for the quick response! I think this will solve my issue. I couldn’t find this in the README or documentation, so it might be helpful to add it there. Thanks again!

**Comment by Taiizor** [comment]
> Thanks for the quick response! I think this will solve my issue. I couldn’t find this in the README or documentation, so it might be helpful to add it there. Thanks again!

If you pull the project again, you shouldn't experience the source issue anymore.

**Comment by arsaey** [comment]
Thanks

**Comment by Taiizor** [comment]
> Thanks

Can you confirm if the issue has been resolved? If so, I'll close this issue.

**Comment by arsaey** [comment]
Yes, the issue has been resolved.
thanks again.
