### ISSUE TITLE
动态壁纸GPU使用率高

### ISSUE THREAD

**Issue by 2916625740** [Taiizor/Sucrose#95]
![Uploading Snipaste_2024-08-19_17-15-18.png…]()

**Comment by Taiizor** [comment]
I can't see the image you uploaded, but resource consumption can vary depending on the type of wallpaper, wallpaper resolution, or the engine/extension used. To find the most suitable option for you, review your engine/extension preferences for the relevant theme type in the wallpaper settings section.
