### ISSUE TITLE
can install new graphics from store

### ISSUE THREAD

**Issue by nasimsamin86** [Taiizor/Sucrose#99]
**Bug Description**

the bug.
![Screenshot (19)](https://github.com/user-attachments/assets/41a85f44-bc28-4148-81dd-9730768e6b33)

**Comment by Taiizor** [comment]
From what I understand from this image, you're using a very old version of Sucrose. You can verify this information yourself in the image below.

![Sucrose-Wallpaper-Engine-Store](https://github.com/user-attachments/assets/1004d36f-9169-458a-a474-52c7134e5cdb)

Please right-click on the Sucrose system tray icon in the taskbar and select 'Check for Updates' from the menu. A visual guide is provided below.

![Sucrose-Wallpaper-Engine-System-Tray](https://github.com/user-attachments/assets/1e44026e-24e0-4eec-96f6-d3888e22f087)

If you encounter an error while checking for updates or are unable to update, you will need to manually install the latest version. To do this, go to [this address](https://github.com/Taiizor/Sucrose?tab=readme-ov-file#download) and download the appropriate version for your system from GitHub. If you're unsure which to choose, you can select the one marked in the image below.

![Sucrose-Wallpaper-Engine-Download-GitHub](https://github.com/user-attachments/assets/196b2765-1a73-41e4-b430-eaf22d318bb1)

HINT: Your system is most likely x64 architecture, but if it is x86, choose the appropriate version.

**Comment by Taiizor** [comment]
@nasimsamin86 Please provide feedback if your issue has been resolved.
